#!/usr/bin/env python3
"""Generate data/offline-manifest.json — the list of files the app downloads for
full offline use (Settings → Offline use → Update data).

The manifest is what makes the download honest: it carries the real byte size of
every file, so the UI can tell the user "26.4 MB" before they commit to it rather
than discovering it mid-download on tournament wifi.

Re-run after adding unit art, a faction JSON, or any core asset:
    python scripts/gen-offline-manifest.py

Groups:
  core  — app shell (html/css/js) + rules & stats data. Small, always synced.
          The shell is read out of sw.js's CORE array, so the download and the
          service worker's precache cannot disagree.
  art   — every unit thumbnail. The bulk of the download.

Full-resolution art (assets/art/*.webp) is deliberately NOT included: every
on-screen view uses thumbUrl(), so full-res is only ever needed for printing,
which is not an offline-at-the-table activity.
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def core_files() -> list[str]:
    """The app shell, read out of sw.js.

    This used to be a hand-kept list with a comment saying it was "kept in sync
    with CORE in sw.js". It was not. It still named js/app.js and the three
    calc-* files, which belong to Dropfleet and are not in this repo, and it
    named none of the twelve DZC modules or either DZC stylesheet -- so the
    download the app offers as "Rules, stats & app" contained 26 MB of art and
    no app. The four missing files printed a warning line each and nobody read
    them.

    Two lists that must agree is one list too many, so there is now one: sw.js
    precaches CORE on install, and this reads the same array.
    """
    src = open(os.path.join(ROOT, 'sw.js'), encoding='utf-8').read()
    body = re.search(r'const CORE\s*=\s*\[(.*?)\];', src, re.S)
    if not body:
        raise SystemExit('sw.js has no CORE array — nothing to build a manifest from')
    out = []
    for raw in re.findall(r"'([^']+)'", body.group(1)):
        path = raw.lstrip('./')
        # './' is the navigation entry; index.html is the file behind it.
        if not path:
            continue
        out.append(path)
    return out

# Directories swept wholesale, with the group they belong to.
DIR_GROUPS = [
    ('core', 'data/dzc', ('.json',)),
    ('core', 'assets/logos', ('.png', '.webp', '.svg', '.ico')),
    # Dropzone UNIT photos. assets/art/* is Dropfleet SHIP art -- 58 MB for a
    # different game -- and is neither deployed nor downloadable any more.
    ('art', 'assets/units', ('.webp',)),
]


def rel_files(subdir, exts):
    """Every file under subdir with one of exts, as repo-relative forward-slash paths."""
    base = os.path.join(ROOT, subdir)
    if not os.path.isdir(base):
        return []
    out = []
    for dirpath, _dirnames, filenames in os.walk(base):
        for fn in sorted(filenames):
            if not fn.lower().endswith(exts):
                continue
            full = os.path.join(dirpath, fn)
            out.append(os.path.relpath(full, ROOT).replace(os.sep, '/'))
    return sorted(out)


def entry(path):
    """{u: url, b: bytes} — short keys because this manifest ships to every client."""
    full = os.path.join(ROOT, path)
    return {'u': './' + path, 'b': os.path.getsize(full)}


def main():
    groups = {'core': [], 'art': []}

    for path in core_files():
        full = os.path.join(ROOT, path)
        if os.path.exists(full):
            groups['core'].append(entry(path))
        else:
            print(f'  ! missing core file, skipped: {path}')

    for group, subdir, exts in DIR_GROUPS:
        found = rel_files(subdir, exts)
        groups[group].extend(entry(p) for p in found)
        print(f'  {group:5s} {subdir:22s} {len(found):4d} files')

    # Dedupe (a file in sw.js CORE may also be swept from a directory),
    # keeping the first occurrence so group assignment stays stable.
    seen = set()
    for name in groups:
        deduped = []
        for e in groups[name]:
            if e['u'] in seen:
                continue
            seen.add(e['u'])
            deduped.append(e)
        groups[name] = deduped

    manifest = {
        '_comment': 'Generated by scripts/gen-offline-manifest.py — do not hand-edit.',
        'groups': [
            {'id': 'core', 'label': 'Rules, stats & app',
             'bytes': sum(e['b'] for e in groups['core']), 'files': groups['core']},
            {'id': 'art', 'label': 'Unit artwork',
             'bytes': sum(e['b'] for e in groups['art']), 'files': groups['art']},
        ],
    }
    manifest['totalFiles'] = sum(len(g['files']) for g in manifest['groups'])
    manifest['totalBytes'] = sum(g['bytes'] for g in manifest['groups'])

    out = os.path.join(ROOT, 'data', 'offline-manifest.json')
    with open(out, 'w', encoding='utf-8') as fh:
        json.dump(manifest, fh, separators=(',', ':'))

    mb = manifest['totalBytes'] / 1048576
    for g in manifest['groups']:
        print(f"  {g['id']:5s} total {g['bytes'] / 1048576:6.1f} MB  ({len(g['files'])} files)")
    print(f"\nWrote data/offline-manifest.json — {manifest['totalFiles']} files, {mb:.1f} MB")


if __name__ == '__main__':
    main()
