#!/usr/bin/env python3
"""Generate data/offline-manifest.json — the list of files the app downloads for
full offline use (Settings → Offline use → Update data).

The manifest is what makes the download honest: it carries the real byte size of
every file, so the UI can tell the user "26.4 MB" before they commit to it rather
than discovering it mid-download on tournament wifi.

Re-run after adding ship art, a faction JSON, or any core asset:
    python scripts/gen-offline-manifest.py

Groups:
  core  — app shell (html/css/js) + rules & stats data. Small, always synced.
  art   — every ship/station/feature thumbnail. The bulk of the download.

Full-resolution art (assets/art/*.webp) is deliberately NOT included: every
on-screen view uses thumbUrl(), so full-res is only ever needed for printing,
which is not an offline-at-the-table activity.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Files the app shell needs to boot with no network. Kept in sync with CORE in sw.js.
CORE_FILES = [
    'index.html',
    'css/app.css',
    'css/mobile-fixes.css',
    'js/rank-insignia.js',
    'js/calc-engine.js',
    'js/calc-data.js',
    'js/calc-ui.js',
    'js/app.js',
    'js/offline-sync.js',
    'js/fleet-sync.js',
    'manifest.webmanifest',
]

# Directories swept wholesale, with the group they belong to.
DIR_GROUPS = [
    ('core', 'data/dzc', ('.json',)),
    ('core', 'assets/logos', ('.png', '.webp', '.svg', '.ico')),
    # Dropzone UNIT photos. assets/art/* is Dropfleet SHIP art -- 58 MB for a
    # different game -- and is neither deployed nor downloadable any more.
    ('art', 'assets/units', ('.webp',)),
]


def rel_files(subdir, exts):
    """Every file under subdir with one of exts, as repo-relative forward-slash paths."""
    base = os.path.join(ROOT, subdir)
    if not os.path.isdir(base):
        return []
    out = []
    for dirpath, _dirnames, filenames in os.walk(base):
        for fn in sorted(filenames):
            if not fn.lower().endswith(exts):
                continue
            full = os.path.join(dirpath, fn)
            out.append(os.path.relpath(full, ROOT).replace(os.sep, '/'))
    return sorted(out)


def entry(path):
    """{u: url, b: bytes} — short keys because this manifest ships to every client."""
    full = os.path.join(ROOT, path)
    return {'u': './' + path, 'b': os.path.getsize(full)}


def main():
    groups = {'core': [], 'art': []}

    for path in CORE_FILES:
        full = os.path.join(ROOT, path)
        if os.path.exists(full):
            groups['core'].append(entry(path))
        else:
            print(f'  ! missing core file, skipped: {path}')

    for group, subdir, exts in DIR_GROUPS:
        found = rel_files(subdir, exts)
        groups[group].extend(entry(p) for p in found)
        print(f'  {group:5s} {subdir:22s} {len(found):4d} files')

    # Dedupe (a file listed in CORE_FILES may also be swept from a directory),
    # keeping the first occurrence so group assignment stays stable.
    seen = set()
    for name in groups:
        deduped = []
        for e in groups[name]:
            if e['u'] in seen:
                continue
            seen.add(e['u'])
            deduped.append(e)
        groups[name] = deduped

    manifest = {
        '_comment': 'Generated by scripts/gen-offline-manifest.py — do not hand-edit.',
        'groups': [
            {'id': 'core', 'label': 'Rules, stats & app',
             'bytes': sum(e['b'] for e in groups['core']), 'files': groups['core']},
            {'id': 'art', 'label': 'Ship artwork',
             'bytes': sum(e['b'] for e in groups['art']), 'files': groups['art']},
        ],
    }
    manifest['totalFiles'] = sum(len(g['files']) for g in manifest['groups'])
    manifest['totalBytes'] = sum(g['bytes'] for g in manifest['groups'])

    out = os.path.join(ROOT, 'data', 'offline-manifest.json')
    with open(out, 'w', encoding='utf-8') as fh:
        json.dump(manifest, fh, separators=(',', ':'))

    mb = manifest['totalBytes'] / 1048576
    for g in manifest['groups']:
        print(f"  {g['id']:5s} total {g['bytes'] / 1048576:6.1f} MB  ({len(g['files'])} files)")
    print(f"\nWrote data/offline-manifest.json — {manifest['totalFiles']} files, {mb:.1f} MB")


if __name__ == '__main__':
    main()
